language: python
python:
- '3.7'
before_install:
- pip install -U pip
- python setup.py install
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov tests
after_success:
- codecov
deploy:
  provider: pypi
  user: hzhao19
  password:
    secure: qkkqjUBm61lfO7KlSMMk1iw7qU8tBg0FXwi3u1mF7nLWc1M/bZJpZZoQ3ayvZbMSiFsJ3+TLNM9CRYcjie0oB+w4cfIO0KnAg5J9AMnW5phIHsOdh5QkaBQksNG/rTLBamGVVxDqAYTV+0SCa3VnLgPSJdZUwC0WuOa6aOCZK7voepraj9RoMDzElrxpvSyKISqt4W8p2Hi8qbYIYQ/jNXM2ZZEZQ1y4JYliRVZJ1zeI9QcS59R9rKg5frUnEA/hVe9uhp8bNSgwa3TYhoA1+Le+K80UapW2Z/ZvIjz9a20BVj+DUrGbM7TRXvRSH9HOpTou/zBJMchs1nh1T6ypvw5sZtqmFEhFR2UVYCUcMUoaGPOrjteQrmbjH0hI7yOfh6DAfwRCn6CErKt3kuTFTu4nbeNgvxVzCHn4E0Z+0zmhKUoa3DXAvpM049VhjMFKKkUg+ii//1qry2GZUEkIHvK1d63UW/zaxMQdgbXtzRSv3x0F4fhbcF9wp6cYCdevVjZau87A6p4fs5FsNQyn5mu1ae9fW0EzyRYyaJcQYq9ZIjQfb+rDzqoSGWY03HimJHvFGm9TgfcVFIH4De1HIvDpamkq1wuNCpD4K8KqB5ydo5o9KvBGhf76KYMcDjde8Is2ijxU2DRSMTaBrEDZrduhxsvJrxZgbSJpx08uyXA=
  on:
    branch: master
    tags: true
  skip_cleanup: true
  skip_existing: true
