language: python
python:
- '3.7'
before_install:
- pip install -U pip
- python setup.py install
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov tests
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Au6qdK+ta0C1caCxS9lZ0Z9KmfSq2uFdhebv5TCJNvZQZrkTNlcfPguTo2bTM9he1ectWqFvwHB26g8Yd/OqmoF9YWG9jNZbiSg7r/lg4qf4g1hAbzUOtEu8KhIXAbGkAbemgH885XowNxVhO8z2os7nVDSv7Px/+Z3bw+nM4rM+wxaQffcfegN86DFpjdt+TGEGg0RHIn8GwcT6z0an1TrfNlMgNH3tjar92je2dtpkgFQOddXo6+JGKZHScvn7vasPt/3/euMjKuCfum8tlDLsrRT3TkueG1Bnj7mE1d2D7hNSX3YT+MLTzk3xgC0RjsnA+UuUOMAlOA4YXxDYEEGYRrAY+UPdGq5KyWe0LV86AuMf8azokAjcGg3zcQBXLc115Ss+wuGSEoQDgrpUDZ6YBupQG1robRa1+bBdJJsAXLMwY1LUMcmw4Z1nFYeG5Tk+9luczdAGDwTKuC6OPT5C7zMACpUqQMDiBTj2XcYJ4gwLa6/FMBlvPT5PxcxNBFVHY6vTf+SRxoUdJYaJIXT6999UupbX7Q0xESWnuPFw0r6EY1eHGfBzwYJid7x0JUgt096Vb1b53MZe3GbdunCDRqDYtFmEvNuQiIBSIExDN5wNvKiwpZbX4dnM6kxBMkKMFj9vA2IAi7lYx0LHM6lG8Mrcq5KUeZfTYK3Ajuw=
  on:
    branch: master
    tags: true
  skip_existing: true
