language: python
python:
- '3.7'
before_install:
- pip install -U pip
- python setup.py install
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov tests
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: S/iuKQl3JRhEIU7dAXCe7VU29gcksudt01yvsWxYv4FQfxWvZ8lUt23Nw4m9HZKb9HV9jGJDQMhA7YkUvOHEGl7ibmWFJA1VIh+p4HkRT/JETBOUIwVLF9NADZjvP6MIaJFIOPynSomEWI8o545TPmW8W48aAt6a8tVm5OTkCKriEYQdTcCIBAvIdGcKNjwRfOiTEYifUBzmdL2Mlcj255HeEuxPAElsw3wL4y1ExdVlMV4gVC1Cer5CKJiS1Hc4RMy6vAoBgMXdn/bVQFjVdxkYIgyFnG54Efi53VpqojNTea854qixz8wxqRRCYXl+S4po6DSbRmMDR8o+fKNz/1qZk/NXkTgBMCo5dtGKO3Aqz7ipzCIg3OjFfzpCDADJ+Thcf4pCqtZ/Srl7CrBEuQ/fMdu9x70IRo4dWjWeYhhj6PSPVkKxRF14EbrL+GNFGd2Cwl2vsK/2UKRsTXR3pjHpjG64VRUEWkWrMsvd3jpFxNjjQ7kBRH6OjI2Vd9ExBfwotrUCqEc3n6kdQoiPfgsmIQ+IhXI3xQ4rc9yDmViA730QX+ewMdCOCehjCSdWXlRua5XTCWxMAkSfAQYTvPneSs2OXaBJcTNX0+gbBEBt6LRBeJ3me4y9LLczg+IX/lLgPeL2V8Q2ysQmLXKoyflefti2eWpOhvAaHOV6pK4=
  on:
    branch: master
    tags: true
  skip_existing: true
