language: python
python:
- '3.7'
before_install:
- pip install -U pip
- python setup.py install
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov tests
after_success:
- codecov
deploy:
  provider: pypi
  user: hzhao19
  password:
    secure: qBgGyOmGd4vWIpFULzi0UV5ABmzSh2ABuqqMiduh4zuBDtsHeNRGqCes2b1ixMr6THqZD7NsI7x5a53ycq0LR1drwiszAr1lERtEAcn30xajncpws3EZfEWB2t/3t1docmOWfZ/zDLRVsrP9t6c63jJP9mwPdR6AnmyggJskRFj9U6wM6er3O4cO4M293Hnc/7XNhp1nXtecHNwBd2U7kl27CAPRquQ3NE7kEM+9FsiUuJdL6kVOjm1dzk+IM6qmri4b1uO33TecIK2o9TVTNM/z+lGrns6xBaV1zwc8Qnu4VYtm9VMgZNv98rrKJuwkhmwDsPk0X4nLCc4OsMwrvxtZAavz8/kM0ijsh/JY8TLb/LeexpJfUJeKmqEAL7YtA7AfJL7HL78Yu6tddqsTh3wPzeJoSlg7cDaItLlJ/sJ2Wkz7RpiDPeDY60xJUXbvYAGz47tKnN5xgRT2Rl7teft0d9Xuu3c3TfjaltvPzCWlk/mT6KjNWUKcq2lAr0IpadQvDjj5i5o+cT2qIzry/n0us7x/IY829PP+I9+UwKD1X9XHYTMYHH87xY2UIsMPysGXGdQQ+lg8f8MgEspjCeStc3Iov+27l3+cYhbn8cPA2cmCyBBKu/4AqvRXZK7JMniyRRhHbTap8cMEFEuSivpuVCnEZ+9SOOCKt+zWxhQ=
  on:
    branch: master
    tags: true
  skip_existing: true
