language: python
python:
- '3.7'
before_install:
- pip install -U pip
- python setup.py install
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov tests
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJGQxMjM0ZDE5LWMyZjctNDEzZC04NTJkLWFjMTJiNTIwOTgzMQACOnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJwaW5pdmVyc2UiXX0sICJ2ZXJzaW9uIjogMX0AAAYgmPMOkWmkjCqNkX2-UXkohsnllDx5kzlM3Jo-zgrvhHM
  on:
    branch: master
    tags: true
  skip_existing: true
